[project]
name = "metric-depth"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.5",
    "open3d>=0.19.0",
    "opencv-python>=4.12.0.88",
    "torch>=2.8.0",
    "torchvision>=0.23.0",
]
